[package]
name = "day-01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = { workspace = true }
nom = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
miette = { workspace = true }
thiserror = { workspace = true }
dhat = { workspace = true }
rstest = { workspace = true }
aho-corasick = "1.1.2"

[dev-dependencies]
divan = { workspace = true }
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "day-01"
path = "benches/benchmarks.rs"
harness = false

[[bench]]
name = "day-01-bench-criterion"
path = "benches/benchmarks-criterion.rs"
harness = false


[features]
dhat-heap = []
